// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Buttin: typeof import('./src/components/buttin.vue')['default']
    FooterMusic: typeof import('./src/components/items/FooterMusic.vue')['default']
    IconList: typeof import('./src/components/home/IconList.vue')['default']
    MusicDetail: typeof import('./src/components/items/MusicDetail.vue')['default']
    MusicList: typeof import('./src/components/home/MusicList.vue')['default']
    PlayList: typeof import('./src/components/items/PlayList.vue')['default']
    SongList: typeof import('./src/components/items/SongList.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
